name: Compare WordPress versions between environments

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  compare-environments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check staging environment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            REMOTE_DIR=~/www/staging.nielslange.de/public_html
            cd "$REMOTE_DIR" || exit 1
            '=== WordPress core ==='
            wp core version --allow-root
            '=== WordPress plugins ==='
            wp plugin list --fields=name,status,version --allow-root
            '=== WordPress themes ==='
            wp theme list --fields=name,status,version --allow-root

      - name: Check production environment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            REMOTE_DIR=~/www/production.nielslange.de/public_html
            cd "$REMOTE_DIR" || exit 1
            '=== WordPress core ==='
            wp core version --allow-root
            '=== WordPress plugins ==='
            wp plugin list --fields=name,status,version --allow-root
            '=== WordPress themes ==='
            wp theme list --fields=name,status,version --allow-root
