name: Check plugin and theme versions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check plugin and theme versions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 60s
          debug: true
          script: |
            echo "=== Current Directory ==="
            pwd
            echo ""
            echo "=== Home Directory Contents ==="
            ls -la ~/
            echo ""
            echo "=== Looking for WordPress installations ==="
            find ~ -name "wp-config.php" -type f 2>/dev/null | head -10
            echo ""
            echo "=== Common web directories ==="
            ls -la /var/www/ 2>/dev/null || echo "No /var/www/ directory"
            ls -la /home/*/public_html/ 2>/dev/null || echo "No public_html directories found"
            ls -la /home/*/htdocs/ 2>/dev/null || echo "No htdocs directories found"
            echo ""
            echo "=== WordPress installations with wp-cli ==="
            wp core version --allow-root 2>/dev/null || echo "WP-CLI not found in current directory"
