name: Check plugin and theme versions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check plugin and theme versions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 60s
          debug: true
          script: |
            echo "=== Exploring www directory ==="
            ls -la ~/www/
            echo ""
            echo "=== Looking for staging.nielslange.de ==="
            find ~/www -name "*staging*" -type d 2>/dev/null
            find ~/www -name "*nielslange*" -type d 2>/dev/null
            echo ""
            echo "=== All directories in www ==="
            find ~/www -type d -maxdepth 3 2>/dev/null
            echo ""
            echo "=== Looking for wp-config.php files ==="
            find ~/www -name "wp-config.php" -type f 2>/dev/null
            echo ""
            echo "=== Checking if WP-CLI is available globally ==="
            which wp 2>/dev/null || echo "WP-CLI not found in PATH"
            wp --version 2>/dev/null || echo "WP-CLI not accessible"
