name: WP inventory compare, print to log

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: read

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch staging versions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            WP_DIR=~/www/staging.nielslange.de/public_html
            cd "$WP_DIR"
            wp plugin list --fields=name,version,update_version,status --format=json --allow-root > "$WP_DIR/plugins.json"
            wp theme  list --fields=name,status,version,update_version --format=json --allow-root > "$WP_DIR/themes.json"
            wp core   version --extra --allow-root > "$WP_DIR/core.json"

      - name: Download staging JSON
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          source: "$WP_DIR/*.json"
          target: "staging"
          overwrite: true

      - name: Fetch production versions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            WP_DIR=~/www/production.nielslange.de/public_html
            cd "$WP_DIR"
            wp plugin list --fields=name,version,update_version,status --format=json --allow-root > "$WP_DIR/plugins.json"
            wp theme  list --fields=name,status,version,update_version --format=json --allow-root > "$WP_DIR/themes.json"
            wp core   version --extra --allow-root > "$WP_DIR/core.json"

      - name: Download production JSON
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          source: "$WP_DIR/*.json"
          target: "production"
          overwrite: true
