name: Compare WordPress versions between environments

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  compare-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fetch staging versions
      - name: Generate staging JSON on remote
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            WP_DIR=~/www/staging.nielslange.de/public_html
            OUT=/tmp/wp-inventory-staging
            mkdir -p "$OUT"
            cd "$WP_DIR"
            wp plugin list --fields=name,version,update_version,status --format=json --allow-root > "$OUT/plugins.json"
            wp theme  list --fields=name,status,version,update_version --format=json --allow-root > "$OUT/themes.json"
            wp core   version --allow-root > "$OUT/core.json"

      - name: Fetch staging JSON to repo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          source: "/tmp/wp-inventory-staging/*.json"
          target: "inventory/staging"
          overwrite: true
          strip_components: 0
          direction: download

      # Fetch production versions
      - name: Generate production JSON on remote
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            WP_DIR=~/www/production.nielslange.de/public_html
            OUT=/tmp/wp-inventory-production
            mkdir -p "$OUT"
            cd "$WP_DIR"
            wp plugin list --fields=name,version,update_version,status --format=json --allow-root > "$OUT/plugins.json"
            wp theme  list --fields=name,status,version,update_version --format=json --allow-root > "$OUT/themes.json"
            wp core   version --allow-root > "$OUT/core.json"

      - name: Fetch production JSON to repo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          source: "/tmp/wp-inventory-production/*.json"
          target: "inventory/production"
          overwrite: true
          strip_components: 0
          direction: download

      - name: Commit changes
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add inventory/
          git diff --cached --quiet || git commit -m "chore, inventory, update"
          git push
