name: WP inventory (artifacts)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Passphrase-free deploy keys for both hosts
      - name: SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
            ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}

      - name: Fetch staging versions
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.STAGING_SSH_USERNAME }}
          SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
        run: |
          set -euo pipefail
          mkdir -p inventory/staging
          SSH_OPTS="-T -p $SSH_PORT -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
          DETECT=$'bash -lc '\''for p in "$PWD" "$HOME/public_html" "$HOME/www/public_html" "/var/www/html" "/srv/www/html" "/usr/share/nginx/html"; do [ -f "$p/wp-config.php" ] || [ -d "$p/wp-includes" ] && echo "$p" && exit; done; echo "$PWD"'\'''
          WP_PATH="$(ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "$DETECT")"
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp plugin list --path='$WP_PATH' --fields=name,version,update_version,status --format=json" > inventory/staging/plugins.json
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp theme  list --path='$WP_PATH' --fields=name,status,version,update_version --format=json" > inventory/staging/themes.json
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp core   version --path='$WP_PATH' --extra" > inventory/staging/core.json

      - name: Fetch production versions
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
        run: |
          set -euo pipefail
          mkdir -p inventory/production
          SSH_OPTS="-T -p $SSH_PORT -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=$HOME/.ssh/known_hosts"
          DETECT=$'bash -lc '\''for p in "$PWD" "$HOME/public_html" "$HOME/www/public_html" "/var/www/html" "/srv/www/html" "/usr/share/nginx/html"; do [ -f "$p/wp-config.php" ] || [ -d "$p/wp-includes" ] && echo "$p" && exit; done; echo "$PWD"'\'''
          WP_PATH="$(ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "$DETECT")"
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp plugin list --path='$WP_PATH' --fields=name,version,update_version,status --format=json" > inventory/production/plugins.json
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp theme  list --path='$WP_PATH' --fields=name,status,version,update_version --format=json" > inventory/production/themes.json
          ssh $SSH_OPTS "$SSH_USER@$SSH_HOST" "wp core   version --path='$WP_PATH' --extra" > inventory/production/core.json

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-inventory-${{ github.run_number }}
          path: inventory/**
          retention-days: 30
