name: Check plugin and theme versions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check plugin and theme versions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 60s
          script: |
            cd ~/www/staging.nielslange.de/public_html
            echo "=== WordPress Installation Info ==="
            wp core version --allow-root
            echo ""
            echo "=== Plugin Status ==="
            wp plugin status --allow-root
            echo ""
            echo "=== Theme Status ==="
            wp theme status --allow-root
            echo ""
            echo "=== Available Plugin Updates ==="
            wp plugin list --update=available --format=table --allow-root
            echo ""
            echo "=== Available Theme Updates ==="
            wp theme list --update=available --format=table --allow-root
            echo ""
            echo "=== Summary ==="
            echo "WordPress Version: $(wp core version --allow-root)"
            echo "Active Theme: $(wp theme status --allow-root | grep 'Active:' | cut -d':' -f2 | xargs)"
            echo "Total Plugins: $(wp plugin list --format=count --allow-root)"
            echo "Active Plugins: $(wp plugin list --status=active --format=count --allow-root)"
            echo "Plugin Updates Available: $(wp plugin list --update=available --format=count --allow-root)"
            echo "Theme Updates Available: $(wp theme list --update=available --format=count --allow-root)"
