name: Compare WordPress versions between environments

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  compare-environments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- STAGING ----------
      - name: Build STAGING reports on remote
        id: staging_build
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            REMOTE_DIR=~/www/staging.nielslange.de/public_html
            cd "$REMOTE_DIR" || exit 1

            # Create staging report directory
            mkdir -p /tmp/staging-report

            # Save WP CLI output to files
            wp core version --allow-root > /tmp/staging-report/core-version.txt
            wp theme list --status=active --field=name --allow-root > /tmp/staging-report/active-theme.txt
            wp theme list --status=active --field=version --allow-root > /tmp/staging-report/active-theme-version.txt
            wp plugin list --format=json --fields=name,status,version --allow-root > /tmp/staging-report/plugins.json
            wp theme list --format=json --fields=name,status,version --allow-root > /tmp/staging-report/themes.json

            # Create combined JSON report
            cat > /tmp/staging-report/staging.json << 'EOF'
            {
              "environment": "STAGING",
              "timestamp": "$(date -u '+%Y-%m-%d %H:%M:%S UTC')",
              "wordpress_version": "$(cat /tmp/staging-report/core-version.txt)",
              "active_theme": "$(cat /tmp/staging-report/active-theme.txt)",
              "active_theme_version": "$(cat /tmp/staging-report/active-theme-version.txt)",
              "plugins": $(cat /tmp/staging-report/plugins.json),
              "themes": $(cat /tmp/staging-report/themes.json)
            }
            EOF

            # List files for verification
            ls -la /tmp/staging-report/
            echo "=== STAGING REPORT CONTENTS ==="
            cat /tmp/staging-report/staging.json

      # ---------- PRODUCTION ----------
      - name: Build PRODUCTION reports on remote
        id: production_build
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          timeout: 30s
          command_timeout: 120s
          script: |
            set -euo pipefail
            REMOTE_DIR=~/www/production.nielslange.de/public_html
            cd "$REMOTE_DIR" || exit 1

            # Create production report directory
            mkdir -p /tmp/production-report

            # Save WP CLI output to files
            wp core version --allow-root > /tmp/production-report/core-version.txt
            wp theme list --status=active --field=name --allow-root > /tmp/production-report/active-theme.txt
            wp theme list --status=active --field=version --allow-root > /tmp/production-report/active-theme-version.txt
            wp plugin list --format=json --fields=name,status,version --allow-root > /tmp/production-report/plugins.json
            wp theme list --format=json --fields=name,status,version --allow-root > /tmp/production-report/themes.json

            # Create combined JSON report
            cat > /tmp/production-report/production.json << 'EOF'
            {
              "environment": "PRODUCTION",
              "timestamp": "$(date -u '+%Y-%m-%d %H:%M:%S UTC')",
              "wordpress_version": "$(cat /tmp/production-report/core-version.txt)",
              "active_theme": "$(cat /tmp/production-report/active-theme.txt)",
              "active_theme_version": "$(cat /tmp/production-report/active-theme-version.txt)",
              "plugins": $(cat /tmp/production-report/plugins.json),
              "themes": $(cat /tmp/production-report/themes.json)
            }
            EOF

            # List files for verification
            ls -la /tmp/production-report/
            echo "=== PRODUCTION REPORT CONTENTS ==="
            cat /tmp/production-report/production.json

      # ---------- DOWNLOAD STAGING REPORTS ----------
      - name: Download STAGING reports
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SSH_HOSTNAME }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          source: /tmp/staging-report/
          target: ./
          overwrite: true
          strip_components: 2

      # ---------- DOWNLOAD PRODUCTION REPORTS ----------
      - name: Download PRODUCTION reports
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
          source: /tmp/production-report/
          target: ./
          overwrite: true
          strip_components: 2

      # ---------- ORGANIZE ARTIFACTS ----------
      - name: Organize downloaded artifacts
        run: |
          mkdir -p artifacts
          mv staging-report/* artifacts/ 2>/dev/null || true
          mv production-report/* artifacts/ 2>/dev/null || true
          ls -la artifacts/

      # ---------- CREATE TEST ARTIFACT ----------
      - name: Create test hello world artifact
        run: |
          echo "Hello World! This is a test artifact." > artifacts/hello-world.txt
          echo "Current timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> artifacts/hello-world.txt
          echo "GitHub Actions is working!" >> artifacts/hello-world.txt

      # ---------- GENERATE COMPARISON ----------
      - name: Generate comparison report
        run: |
          echo "=== ENVIRONMENT COMPARISON REPORT ===" > artifacts/comparison.txt
          echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> artifacts/comparison.txt
          echo "" >> artifacts/comparison.txt

          # Parse JSON files and compare
          if [ -f artifacts/staging.json ] && [ -f artifacts/production.json ]; then
            echo "✅ Both environment reports generated successfully" >> artifacts/comparison.txt
            echo "" >> artifacts/comparison.txt

            # Extract WordPress versions
            STAGING_WP=$(jq -r '.wordpress_version' artifacts/staging.json 2>/dev/null || echo "Unknown")
            PROD_WP=$(jq -r '.wordpress_version' artifacts/production.json 2>/dev/null || echo "Unknown")

            echo "WordPress Versions:" >> artifacts/comparison.txt
            echo "  STAGING: $STAGING_WP" >> artifacts/comparison.txt
            echo "  PRODUCTION: $PROD_WP" >> artifacts/comparison.txt
            echo "" >> artifacts/comparison.txt

            # Extract active themes
            STAGING_THEME=$(jq -r '.active_theme' artifacts/staging.json 2>/dev/null || echo "Unknown")
            PROD_THEME=$(jq -r '.active_theme' artifacts/production.json 2>/dev/null || echo "Unknown")

            echo "Active Themes:" >> artifacts/comparison.txt
            echo "  STAGING: $STAGING_THEME" >> artifacts/comparison.txt
            echo "  PRODUCTION: $PROD_THEME" >> artifacts/comparison.txt
            echo "" >> artifacts/comparison.txt

            # Count plugins
            STAGING_PLUGINS=$(jq '.plugins | length' artifacts/staging.json 2>/dev/null || echo "0")
            PROD_PLUGINS=$(jq '.plugins | length' artifacts/production.json 2>/dev/null || echo "0")

            echo "Plugin Counts:" >> artifacts/comparison.txt
            echo "  STAGING: $STAGING_PLUGINS plugins" >> artifacts/comparison.txt
            echo "  PRODUCTION: $PROD_PLUGINS plugins" >> artifacts/comparison.txt
          else
            echo "❌ Failed to generate environment reports" >> artifacts/comparison.txt
            echo "Files found:" >> artifacts/comparison.txt
            ls -la artifacts/ >> artifacts/comparison.txt
          fi

      # ---------- DISPLAY SUMMARY ----------
      - name: Display comparison summary
        run: |
          echo "=== COMPARISON SUMMARY ==="
          cat artifacts/comparison.txt
          echo
          echo "=== FILES IN ARTIFACTS ==="
          ls -la artifacts/
          echo
          echo "=== JSON PREVIEW - STAGING ==="
          if [ -f artifacts/staging.json ]; then
            head -c 300 artifacts/staging.json
          else
            echo "No staging data found"
          fi
          echo
          echo "=== JSON PREVIEW - PRODUCTION ==="
          if [ -f artifacts/production.json ]; then
            head -c 300 artifacts/production.json
          else
            echo "No production data found"
          fi

      # ---------- UPLOAD ARTIFACTS ----------
      - name: Upload staging artifact
        uses: actions/upload-artifact@v4
        with:
          name: staging-wordpress-report
          path: artifacts/staging.json
          retention-days: 30

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-wordpress-report
          path: artifacts/production.json
          retention-days: 30

      - name: Upload comparison report
        uses: actions/upload-artifact@v4
        with:
          name: comparison-report
          path: artifacts/comparison.txt
          retention-days: 30

      - name: Upload hello world test
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-test
          path: artifacts/hello-world.txt
          retention-days: 30
