name: WP inventory

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add both keys, useful when staging and production use different keys
      - name: SSH agent, add staging key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          ssh-passphrase:  ${{ secrets.STAGING_SSH_PASSPHRASE }}

      - name: SSH agent, add production key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          ssh-passphrase:  ${{ secrets.PRODUCTION_SSH_PASSPHRASE }}

      - name: Known hosts
        run: |
          ssh-keyscan -p "${{ secrets.STAGING_SSH_PORT }}"   "${{ secrets.STAGING_SSH_HOSTNAME }}"   >> ~/.ssh/known_hosts
          ssh-keyscan -p "${{ secrets.PRODUCTION_SSH_PORT }}" "${{ secrets.PRODUCTION_SSH_HOSTNAME }}" >> ~/.ssh/known_hosts

      - name: Fetch staging versions
        env:
          SSH_HOST:  ${{ secrets.STAGING_SSH_HOSTNAME }}
          SSH_USER:  ${{ secrets.STAGING_SSH_USERNAME }}
          SSH_PORT:  ${{ secrets.STAGING_SSH_PORT }}
          WP_PATH:   ${{ secrets.STAGING_WP_PATH }}          # e.g. /var/www/html or /home/user/public_html
          WP_BIN:    ${{ secrets.STAGING_WP_BIN || 'wp' }}   # absolute path if needed, else "wp"
        run: |
          set -euo pipefail
          mkdir -p inventory/staging
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN plugin list --fields=name,version,update_version,status --format=json" > inventory/staging/plugins.json
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN theme  list --fields=name,status,version,update_version --format=json" > inventory/staging/themes.json
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN core   version --extra --format=json" > inventory/staging/core.json

      - name: Fetch production versions
        env:
          SSH_HOST:  ${{ secrets.PRODUCTION_SSH_HOSTNAME }}
          SSH_USER:  ${{ secrets.PRODUCTION_SSH_USERNAME }}
          SSH_PORT:  ${{ secrets.PRODUCTION_SSH_PORT }}
          WP_PATH:   ${{ secrets.PRODUCTION_WP_PATH }}
          WP_BIN:    ${{ secrets.PRODUCTION_WP_BIN || 'wp' }}
        run: |
          set -euo pipefail
          mkdir -p inventory/production
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN plugin list --fields=name,version,update_version,status --format=json" > inventory/production/plugins.json
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN theme  list --fields=name,status,version,update_version --format=json" > inventory/production/themes.json
          ssh -T -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd '$WP_PATH' && $WP_BIN core   version --extra --format=json" > inventory/production/core.json

      - name: Commit changes
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add inventory/
          git diff --cached --quiet || git commit -m "chore, inventory, update"
          git push
